### ISSUE TITLE
ImportError: No module named 'cairo' 

### ISSUE THREAD

**Issue by luckydonald** [Kozea/pygal#221]
When issuing ```. render_to_png()``` an import error occurs:
```python
#bar_chart defined like in the example code.
bar_chart.render_to_png()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/luckydonald/Documents/Programmieren/Python/bot/virtualenv3.4.3/lib/python3.4/site-packages/pygal/ghost.py", line 169, in render_to_png
    import cairosvg
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/luckydonald/Documents/Programmieren/Python/bot/virtualenv3.4.3/lib/python3.4/site-packages/cairosvg/__init__.py", line 27, in <module>
    from . import surface
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/luckydonald/Documents/Programmieren/Python/bot/virtualenv3.4.3/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 30, in <module>
    import cairo  # pycairo
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: No module named 'cairo'
```
System:
```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Mac OS 10.9.5
```

**Comment by luckydonald** [comment]
The other import, 2 lines above, ```import cairocffi as cairo``` fails with the follwoing stack trace:
```python
import cairocffi as cairo
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/luckydonald/Documents/Programmieren/Python/bot/virtualenv3.4.3/lib/python3.4/site-packages/cairocffi/__init__.py", line 15, in <module>
    from . import constants
ImportError: cannot import name 'constants'
```

**Comment by luckydonald** [comment]
Suddenly it did work.
- I installed ```cairo``` and ```py2cairo``` with ```brew install ...```,
- reinstalled the pip packages ```cairocffi cffi CairoSVG lxml``` and
- finally rebooted.    

Something like that...

For reference, my installed packages list:
```shell
dhcp233-007:telegram-bot luckydonald$ brew list
binutils	freetype	glib		jpeg		libffi		libtiff		openssl		py2cairo	readline	webp
cairo		gdbm		htop-osx	libconfig	libmagic	little-cms	pixman		python		rename		wget
fontconfig	gettext		jansson		libevent	libpng		lua		pkg-config	python3		sqlite		xz
```
```shell
(virtualenv3.4.3)dhcp233-007:telegram-bot luckydonald$ pip list
beautifulsoup4 (4.3.2)
blessings (1.6)
cairocffi (0.7)
CairoSVG (1.0.14)
cffi (1.1.2)
cssselect (0.9.1)
DictObject (0.1.0)
emoji (0.2)
feedparser (5.2.0)
fuzzywuzzy (0.5.0)
ipgetter (0.6)
lxml (3.4.4)
parsedatetime (1.4)
Pillow (2.8.2)
pip (7.0.3)
pycparser (2.13)
pygal (1.7.0)
python-dateutil (2.4.2)
python-forecastio (1.3.2)
python-Levenshtein (0.12.0)
python-magic (0.4.6)
pytz (2015.4)
qrcode (5.1)
requests (2.7.0)
setuptools (17.1.1)
six (1.9.0)
svn (0.3.33)
tinycss (0.3)
```

**Comment by luckydonald** [comment]
This was what I stumbled on, while searching for a way to fix that.
https://github.com/Kozea/CairoSVG/issues/28
https://github.com/SimonSapin/cairocffi/issues/29
