### ISSUE TITLE
Issue with XY graphs with datetimes in pygal==2.0.0

### ISSUE THREAD

**Issue by mklauber** [Kozea/pygal#251]
Hey I'm seeing a strange issue in pygal 2.0.0.  I've got a XY chart with multiple series of (datetime, value) objects.  They do not all have the same number of objects, or from the same dates.  When it tries to render the chart it raises the following exception.  This exception is raised even if I tell it `show_x_labels=False`.  Any ideas?

```
Traceback (most recent call last):
  File "__init__.py", line 142, in <module>
    charting.histogram(vehicles)
  File "/charting.py", line 34, in histogram
    histogram.render_to_file('histogram.svg') 
  File "lib/python2.7/site-packages/pygal/graph/public.py", line 111, in render_to_file
    f.write(self.render(is_unicode=True, **kwargs))
  File "lib/python2.7/site-packages/pygal/graph/public.py", line 49, in render
    self.setup(**kwargs)
  File "lib/python2.7/site-packages/pygal/graph/base.py", line 217, in setup
    self._draw()
  File "lib/python2.7/site-packages/pygal/graph/graph.py", line 762, in _draw
    self._compute_x_labels()
  File "lib/python2.7/site-packages/pygal/graph/dual.py", line 33, in _compute_x_labels
    self.order_min, self.min_scale, self.max_scale
  File "lib/python2.7/site-packages/pygal/util.py", line 182, in compute_scale
    order = round(log10(max(abs(min_), abs(max_)))) - 1
TypeError: bad operand type for abs(): 'datetime.datetime'
```

**Comment by paradoxxxzero** [comment]
That's not strange, datetime are now usable in pygal as-is. [DatetimeLine](http://www.pygal.org/en/latest/documentation/types/xy.html#datetime) seems to be exactly what you need though.
