### ISSUE TITLE
Date example not working

### ISSUE THREAD

**Issue by psirotkin** [Kozea/pygal#256]
When I try running the [Date example](http://www.pygal.org/en/latest/documentation/types/xy.html#date), I get the following error:

    Traceback (most recent call last):
      File "<input>", line 17, in <module>
      File "C:\Python27\lib\site-packages\pygal\graph\public.py", line 49, in render
        self.setup(**kwargs)
      File "C:\Python27\lib\site-packages\pygal\graph\base.py", line 213, in setup
        self._draw()
      File "C:\Python27\lib\site-packages\pygal\graph\graph.py", line 778, in _draw
        self._compute_x_labels()
      File "C:\Python27\lib\site-packages\pygal\graph\dual.py", line 45, in _compute_x_labels
        pos = self._x_adapt(float(x_label))
    TypeError: float() argument must be a string or a number

I guess I must be doing something wrong, but I can't figure out what that would be...

**Comment by paradoxxxzero** [comment]
Thanks for the report!

**Comment by psirotkin** [comment]
Thanks, works fine now!
