### ISSUE TITLE
How to use google fonts?

### ISSUE THREAD

**Issue by darklow** [Kozea/pygal#273]
Could you help please with how to include custom google fonts?
Documentation says all i need to do is specify:
```py
style = Style(font_family='googlefont:Raleway')
```
But if i do so i got error. Do i have to import somehow google font before?
PS. I am using pygal serverside and generating PNG with render_to_png
Thanks 

```py
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/project/stats/management/commands/__init__.py", line 27, in execute
    return super(CustomBaseCommand, self).execute(*args, **options)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/project/stats/management/commands/reports.py", line 31, in handle
    getattr(self, 'handle_%s' % self.action)(**kwargs)
  File "/home/vagrant/project/stats/management/commands/reports.py", line 42, in handle_make
    gen_report(user)
  File "/home/vagrant/project/stats/data/reports.py", line 28, in gen_report
    send_to_user(user, 'report', extra_vars=pr.get_mail_context(user))
  File "/home/vagrant/project/user/models.py", line 195, in get_mail_context
    data.update(report_data(user or self.user, self))
  File "/home/vagrant/project/stats/data/reports.py", line 58, in report_data
    data = rb.get_mail_context()
  File "/home/vagrant/project/stats/data/reports.py", line 76, in get_mail_context
    self.prepare()
  File "/home/vagrant/project/stats/data/reports.py", line 87, in prepare
    chart_file = self.render_stats_chart(group_data['chart_data'])
  File "/home/vagrant/project/stats/data/reports.py", line 164, in render_stats_chart
    content = chart.render_to_png(fn)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/pygal/graph/public.py", line 117, in render_to_png
    bytestring=self.render(**kwargs), write_to=filename, dpi=dpi)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/cairosvg/__init__.py", line 43, in <lambda>
    surface_type.convert(*args, **kwargs))(_surface_type)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/cairosvg/surface/__init__.py", line 101, in convert
    tree = Tree(**kwargs)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/cairosvg/parser.py", line 309, in __init__
    apply_stylesheets(self)
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/cairosvg/css.py", line 121, in apply_stylesheets
    for rule in find_style_rules(tree):
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/cairosvg/css.py", line 85, in find_style_rules
    for stylesheet in find_stylesheets(tree.xml_tree, tree.url):
  File "/home/vagrant/envs/project/lib/python2.7/site-packages/cairosvg/css.py", line 52, in find_stylesheets
    path = os.path.join(os.path.dirname(url), filename)
  File "/home/vagrant/envs/project/lib/python2.7/posixpath.py", line 120, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

```

**Comment by paradoxxxzero** [comment]
Does it work when rendering to svg ?

Le dim. 11 oct. 2015 13:05, Kaspars Sprogis <notifications@github.com> a
écrit :

**Comment by darklow** [comment]
Tried rendering SVG but it doesn't work.
It doesn't throw any errors while generating and SVG can be open, but if i open it with browser i can see two errors:

**Comment by darklow** [comment]
Ok, now i can confirm, if i open .SVG through webserver it works.
But for offline / server-side PNG it fails with an error.

**Comment by paradoxxxzero** [comment]
Okay maybe cairosvg does not handle importing remote fonts very well. As
for offline chart, this is normal.

Le dim. 11 oct. 2015 13:39, Kaspars Sprogis <notifications@github.com> a
écrit :

**Comment by darklow** [comment]
Well it's a nice feature to have, but not like most required one.
You can close the issue, if there is no easy fix. Thanks

**Comment by liZe** [comment]
Yes, CairoSVG can't handle online fonts, and there's no easy fix because Cairo needs the fonts to be installed.
