### ISSUE TITLE
Python 3 installer fails with unicode problem

### ISSUE THREAD

**Issue by hjwp** [Kozea/pygal#277]
```
root@fe18310c16df:~# pip3 install pygal
Collecting pygal
  Using cached pygal-2.0.8.tar.gz
Building wheels for collected packages: pygal
  Running setup.py bdist_wheel for pygal
  Complete output from command /usr/local/bin/python3.4 -c "import setuptools;__file__='/tmp/pip-build-55nheusf/pygal/setup.py';exec(compile(open(__file__).read().replace('\r
\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpgo97cfsbpip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 127: ordinal not in range(128)
```

**Comment by paradoxxxzero** [comment]
Can you try updating your pip for python 3 ?

**Comment by hjwp** [comment]
I'm running pip 7.1.2 which I think is the latest...

**Comment by hjwp** [comment]
OK, I can't repro it now, suspect it was a glitch.
