### ISSUE TITLE
lxml 3.5: ValueError: Invalid PI name 'b'xml''

### ISSUE THREAD

**Issue by georgevreilly** [Kozea/pygal#282]
Trying to run [nikola build](https://getnikola.com/getting-started.html) with lxml's master branch (lxml-3.5.0b1), I get `ValueError: Invalid PI name 'b'xml''` thanks to Pygal.

*Update*: lxml 3.5 has since been released to PyPI

This is a brand new site, created with `nikola init`

    (devblog)$ (master) nikola build
    Scanning posts....done!
    .  render_posts:cache/stories/charts.html
    ########################################
    TaskError - taskid:render_posts:cache/stories/charts.html
    PythonAction Error
    Traceback (most recent call last):
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/doit/action.py", line 383, in execute
        returned_value = self.py_callable(*self.args, **kwargs)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/nikola/post.py", line 485, in compile
        self.is_two_file),
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/nikola/plugins/compile/rest/__init__.py", line 99, in compile_html
        output, error_level, deps = self.compile_html_string(data, source, is_two_file)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/nikola/plugins/compile/rest/__init__.py", line 85, in compile_html_string
        }, logger=self.logger, source_path=source_path, l_add_ln=add_ln, transforms=self.site.rst_transforms)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/nikola/plugins/compile/rest/__init__.py", line 274, in rst2html
        pub.publish(enable_exit_status=enable_exit_status)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
        self.settings)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/readers/__init__.py", line 72, in read
        self.parse()
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
        self.parser.parse(self.input, document)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
        self.statemachine.run(inputlines, document, inliner=self.inliner)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
        input_source=document['source'])
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2301, in explicit_markup
        self.explicit_list(blank_finish)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2331, in explicit_list
        match_titles=self.state_machine.match_titles)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
        node=node, match_titles=match_titles)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
        results = StateMachineWS.run(self, input_lines, input_offset)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2604, in explicit_markup
        nodelist, blank_finish = self.explicit_construct(match)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
        return method(self, expmatch)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
        directive_class, match, type_name, option_presets)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
        result = directive_instance.run()
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/nikola/plugins/compile/rest/chart.py", line 161, in run
        data = chart.render().decode('utf8')
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/pygal/graph/public.py", line 49, in render
        self.setup(**kwargs)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/pygal/graph/base.py", line 196, in setup
        self.svg = Svg(self)
      File "/Users/georgevreilly/.virtualenvs/devblog/lib/python3.5/site-packages/pygal/svg.py", line 51, in __init__
        u('xml'), u("version='1.0' encoding='utf-8'"))]
      File "src/lxml/lxml.etree.pyx", line 3039, in lxml.etree.ProcessingInstruction (src/lxml/lxml.etree.c:76170)
    ValueError: Invalid PI name 'b'xml''

Seems to be due to [lxml: Add validation for PI, Comment and CDATA content](https://github.com/lxml/lxml/commit/3b77ce2ff6f009969f90f75f4485e7b0944a9e91)

**Comment by georgevreilly** [comment]
The [Wikipedia article on Processing Instructions](https://en.wikipedia.org/wiki/Processing_Instruction#Syntax) says:

> The XML Declaration at the beginning of an XML document (shown below) is not a processing instruction, however its similar syntax has often resulted in it being referred to as a processing instruction.[5]
> `<?xml version="1.0" encoding="UTF-8" ?>`

**Comment by georgevreilly** [comment]
Note that [lxml 3.5](https://pypi.python.org/pypi/lxml/3.5.0) is now released to PyPI.

**Comment by sirlark** [comment]
Ditto, using pygal in a django app, and getting the following for all pygal plots

	Traceback:
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
	  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
	  22.                 return view_func(request, *args, **kwargs)
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/ReportFrameWork/views.py" in plot
	  158.     content = rModule.reportObject.render_plot(args) 
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/ReportFrameWork/reports/reports.py" in render_plot
	  749.             return PlotContent(plot.render(), 'image/svg+xml')
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/pygal/graph/public.py" in render
	  49.         self.setup(**kwargs)
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/pygal/graph/base.py" in setup
	  190.         self.svg = Svg(self)
	File "/home/sirlark/.virtualenvs/proj_x/lib/python2.7/site-packages/pygal/svg.py" in __init__
	  51.                 u('xml'), u("version='1.0' encoding='utf-8'"))]

**Comment by georgevreilly** [comment]
I've attached a hacky patch that lets me run [Nikola](https://getnikola.com). It's not intended as a real fix.

[lxml-workaround.patch.txt](https://github.com/Kozea/pygal/files/35179/lxml-workaround.patch.txt)

**Comment by paradoxxxzero** [comment]
Thanks for the report

**Comment by TiantianUpup** [comment]
so how to solve it.I meet this problem.after reading this,i still don't konw the reason
my error code:
 File "src\lxml\lxml.etree.pyx", line 3039, in lxml.etree.ProcessingInstruction (src\lxml\lxml.etree.c:77236)
ValueError: Invalid PI name 'b'xml''
